
package com.example.client.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWebserviceService", targetNamespace = "http://sms.adenon.com/dbop", wsdlLocation = "http://127.0.0.1:9999/ws?wsdl")
public class MyWebserviceService
    extends Service
{

    private final static URL MYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVICESERVICE_EXCEPTION;
    private final static QName MYWEBSERVICESERVICE_QNAME = new QName("http://sms.adenon.com/dbop", "MyWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVICESERVICE_WSDL_LOCATION = url;
        MYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public MyWebserviceService() {
        super(__getWsdlLocation(), MYWEBSERVICESERVICE_QNAME);
    }

    public MyWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWEBSERVICESERVICE_QNAME, features);
    }

    public MyWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, MYWEBSERVICESERVICE_QNAME);
    }

    public MyWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWEBSERVICESERVICE_QNAME, features);
    }

    public MyWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyWebservice
     */
    @WebEndpoint(name = "MyWebservicePort")
    public MyWebservice getMyWebservicePort() {
        return super.getPort(new QName("http://sms.adenon.com/dbop", "MyWebservicePort"), MyWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebservice
     */
    @WebEndpoint(name = "MyWebservicePort")
    public MyWebservice getMyWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sms.adenon.com/dbop", "MyWebservicePort"), MyWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw MYWEBSERVICESERVICE_EXCEPTION;
        }
        return MYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
