
package com.example.client.test;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MyWebServiceException", targetNamespace = "http://sms.adenon.com/dbop")
public class MyWebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MyWebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MyWebServiceException_Exception(String message, MyWebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MyWebServiceException_Exception(String message, MyWebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.client.test.MyWebServiceException
     */
    public MyWebServiceException getFaultInfo() {
        return faultInfo;
    }

}
