
package com.example.client.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebservice", targetNamespace = "http://sms.adenon.com/dbop")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebservice {


    /**
     * 
     * @return
     *     returns com.example.client.test.CarObject
     */
    @WebMethod
    @WebResult(name = "car", targetNamespace = "")
    @RequestWrapper(localName = "findCar", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.FindCar")
    @ResponseWrapper(localName = "findCarResponse", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.FindCarResponse")
    @Action(input = "http://sms.adenon.com/dbop/MyWebservice/findCarRequest", output = "http://sms.adenon.com/dbop/MyWebservice/findCarResponse")
    public CarObject findCar();

    /**
     * 
     * @param carId
     * @return
     *     returns com.example.client.test.CarObject
     * @throws MyWebServiceException_Exception
     */
    @WebMethod(action = "saveCar")
    @WebResult(name = "car", targetNamespace = "")
    @RequestWrapper(localName = "saveCar", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.SaveCar")
    @ResponseWrapper(localName = "saveCarResponse", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.SaveCarResponse")
    @Action(input = "saveCar", output = "http://sms.adenon.com/dbop/MyWebservice/saveCarResponse", fault = {
        @FaultAction(className = MyWebServiceException_Exception.class, value = "http://sms.adenon.com/dbop/MyWebservice/saveCar/Fault/MyWebServiceException")
    })
    public CarObject saveCar(
        @WebParam(name = "carId", targetNamespace = "")
        long carId)
        throws MyWebServiceException_Exception
    ;

    /**
     * 
     * @param carId
     * @return
     *     returns com.example.client.test.CarObject
     */
    @WebMethod(action = "deleteCar")
    @WebResult(name = "car", targetNamespace = "")
    @RequestWrapper(localName = "deleteCar", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.DeleteCar")
    @ResponseWrapper(localName = "deleteCarResponse", targetNamespace = "http://sms.adenon.com/dbop", className = "com.example.client.test.DeleteCarResponse")
    @Action(input = "deleteCar", output = "http://sms.adenon.com/dbop/MyWebservice/deleteCarResponse")
    public CarObject deleteCar(
        @WebParam(name = "carId", targetNamespace = "")
        long carId);

}
