
package com.java.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSSecurity", targetNamespace = "http://security.ws.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSSecurity {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "secureHello", targetNamespace = "http://security.ws.java.com/", className = "com.java.ws.client.SecureHello")
    @ResponseWrapper(localName = "secureHelloResponse", targetNamespace = "http://security.ws.java.com/", className = "com.java.ws.client.SecureHelloResponse")
    @Action(input = "http://security.ws.java.com/WSSecurity/secureHelloRequest", output = "http://security.ws.java.com/WSSecurity/secureHelloResponse")
    public String secureHello();

}
