
package com.client.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSObjectService", targetNamespace = "http://ws.ws.metod.com/", wsdlLocation = "http://localhost:7070/WSProject/WSObject?wsdl")
public class WSObjectService
    extends Service
{

    private final static URL WSOBJECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSOBJECTSERVICE_EXCEPTION;
    private final static QName WSOBJECTSERVICE_QNAME = new QName("http://ws.ws.metod.com/", "WSObjectService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7070/WSProject/WSObject?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSOBJECTSERVICE_WSDL_LOCATION = url;
        WSOBJECTSERVICE_EXCEPTION = e;
    }

    public WSObjectService() {
        super(__getWsdlLocation(), WSOBJECTSERVICE_QNAME);
    }

    public WSObjectService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSOBJECTSERVICE_QNAME, features);
    }

    public WSObjectService(URL wsdlLocation) {
        super(wsdlLocation, WSOBJECTSERVICE_QNAME);
    }

    public WSObjectService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSOBJECTSERVICE_QNAME, features);
    }

    public WSObjectService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSObjectService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSObject
     */
    @WebEndpoint(name = "WSObjectPort")
    public WSObject getWSObjectPort() {
        return super.getPort(new QName("http://ws.ws.metod.com/", "WSObjectPort"), WSObject.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSObject
     */
    @WebEndpoint(name = "WSObjectPort")
    public WSObject getWSObjectPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ws.metod.com/", "WSObjectPort"), WSObject.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSOBJECTSERVICE_EXCEPTION!= null) {
            throw WSOBJECTSERVICE_EXCEPTION;
        }
        return WSOBJECTSERVICE_WSDL_LOCATION;
    }

}
