
package com.client.mtom;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSObject", targetNamespace = "http://ws.ws.metod.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSObject {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "testVoid", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.TestVoid")
    public void testVoid();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadData", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.UploadData")
    @ResponseWrapper(localName = "uploadDataResponse", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.UploadDataResponse")
    public String uploadData(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadData", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.DownloadData")
    @ResponseWrapper(localName = "downloadDataResponse", targetNamespace = "http://ws.ws.metod.com/", className = "com.client.mtom.DownloadDataResponse")
    public byte[] downloadData();

}
